### ISSUE TITLE
Class types defined in different services are created twice

### ISSUE THREAD

**Issue by djungelorm** [djungelorm/krpc#109]
A class type defined in service A, and used in service B is created twice in the python client. Leads to issues such as:
```
Traceback (most recent call last):
  File "test_control.py", line 51, in test_yaw_control
    testingtools.clear_rotation(self.vessel)
  File "/home/alex/workspaces/ksp/krpc/test/kRPCSpaceCenterTest/testingtools.py", line 117, in clear_rotation
    conn.testing_tools.clear_rotation(vessel)
  File "/home/alex/workspaces/ksp/krpc/test/kRPCSpaceCenterTest/env2/local/lib/python2.7/site-packages/krpc/service.py", line 128, in <lambda>
    param_names=param_names, param_types=param_types, return_type=return_type)
  File "/home/alex/workspaces/ksp/krpc/test/kRPCSpaceCenterTest/env2/local/lib/python2.7/site-packages/krpc/service.py", line 24, in _invoke
    param_names, param_types, return_type)
  File "/home/alex/workspaces/ksp/krpc/test/kRPCSpaceCenterTest/env2/local/lib/python2.7/site-packages/krpc/client.py", line 110, in _invoke
    request = self._build_request(service, procedure, args, kwargs, param_names, param_types, return_type)
  File "/home/alex/workspaces/ksp/krpc/test/kRPCSpaceCenterTest/env2/local/lib/python2.7/site-packages/krpc/client.py", line 151, in _build_request
    argument.value = encode_argument(i, arg)
  File "/home/alex/workspaces/ksp/krpc/test/kRPCSpaceCenterTest/env2/local/lib/python2.7/site-packages/krpc/client.py", line 139, in encode_argument
    (service, procedure, i, typ.python_type, type(value), value))
TypeError: TestingTools.ClearRotation() argument 0 must be a <class 'krpc.types.Vessel'>, got a <class 'krpc.types.Vessel'> (<SpaceCenter.Vessel object #22>)
```

**Comment by djungelorm** [comment]
This bug is actually caused when trying to pass an object returned by one connection, to a procedure on another connection. They should have identical types, but two separate python class types are created for each.

**Comment by djungelorm** [comment]
#110
