### ISSUE TITLE
stream context manager returns Stream instead of variable

### ISSUE THREAD

**Issue by baloan** [djungelorm/krpc#138]
I've tried this
```
    with cx.stream(resources.amount, 'SolidFuel') as fuel:
        # fuel = resources.amount('SolidFuel')
        while fuel > 0.1:
            time.sleep(0.1)
            print("Fuel: {}".format(fuel))
        control.activate_next_stage()
```
but hit this roadblock
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Apps\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Apps\Python34\lib\threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Andreas\workspace\sandbox\src\vessels\surveyor.py", line 26, in surveyor1
    while fuel > 0.1:
TypeError: unorderable types: Stream() > float()
```
According to the docs ```fuel``` should return the amount of solidfuel, right?

**Comment by djungelorm** [comment]
I think you need ``fuel()`` instead of ``fuel``.

``fuel`` is a stream object, and calling it with () will get the most up to date value.

**Comment by djungelorm** [comment]
Looks like I made a mistake in the docs, sorry!
