### ISSUE TITLE
SpaceCenter.active_vessel raises ugly exception while in VAB

### ISSUE THREAD

**Issue by borogove** [djungelorm/krpc#97]
Referencing active_vessel while in the VAB throws a messy, deep exception. It might be nicer to return None.

<code>
Traceback (most recent call last):
  File "./console.py", line 128, in <module>
    curses.wrapper( mission.main )
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/russell/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program/Mission Control/mission.py", line 633, in main
    m.update()
  File "/Users/russell/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program/Mission Control/mission.py", line 213, in update
    self.get_common()
  File "/Users/russell/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program/Mission Control/mission.py", line 145, in get_common
    vessel = center.active_vessel
  File "/Library/Python/2.7/site-packages/krpc/service.py", line 134, in <lambda>
    fget = lambda s: getattr(self, _to_snake_case(getter.name))()
  File "/Library/Python/2.7/site-packages/krpc/service.py", line 121, in <lambda>
    param_names=param_names, param_types=param_types, return_type=return_type)
  File "/Library/Python/2.7/site-packages/krpc/service.py", line 24, in _invoke
    param_names, param_types, return_type)
  File "/Library/Python/2.7/site-packages/krpc/client.py", line 113, in _invoke
    raise RPCError(response.error)
krpc.error.RPCError: KRPC.Service.RPCException: Procedure not available in game scene 'Editor'
  at KRPC.Service.Services.HandleRequest (KRPC.Service.Scanner.ProcedureSignature procedure, System.Object[] arguments) [0x00000] in <filename unknown>:0 
  at KRPC.Service.Services.HandleRequest (KRPC.Service.Scanner.ProcedureSignature procedure, KRPC.Schema.KRPC.Request request) [0x00000] in <filename unknown>:0 
  at KRPC.Service.RequestContinuation.Run () [0x00000] in <filename unknown>:0 
  at KRPC.KRPCServer.ExecuteContinuation (KRPC.Service.RequestContinuation continuation) [0x00000] in <filename unknown>:0  
</code>

**Comment by djungelorm** [comment]
It is indeed ugly... I'll change it so that the C# stack trace isn't shown, just the error message (which in this case is "Procedure not available in game scene 'Editor'")

The full stack trace is however useful for debugging the server code, so I'll add a configuration option to settings.cfg to enable display of the C# stack trace if desired.

As a side note, the reason this returns an error rather than None is that the entire SpaceCenter service is configured to only be available in the 'Flight' game scene. So the RPC never reaches SpaceCenter.ActiveVessel (This will probably change in future as bits of the SpaceCenter service would be useful from the Editor view.)

**Comment by djungelorm** [comment]
Is this an acceptable error message?

```
Traceback (most recent call last):
  File "/home/alex/workspaces/ksp/krpc/python/krpc/test/test_client.py", line 28, in test_error
    self.conn.test_service.throw_argument_exception()
  File "/home/alex/workspaces/ksp/krpc/python/krpc/service.py", line 122, in <lambda>
    param_names=param_names, param_types=param_types, return_type=return_type)
  File "/home/alex/workspaces/ksp/krpc/python/krpc/service.py", line 25, in _invoke
    param_names, param_types, return_type)
  File "/home/alex/workspaces/ksp/krpc/python/krpc/client.py", line 113, in _invoke
    raise RPCError(response.error)
RPCError: Procedure not available in game scene 'Editor'
```

I'm hesitant to somehow hide the python stack trace. If you'd prefer that that wasn't shown either, you should probably put a try ... catch around your code, e.g.:

```
try:
    ... your kRPC code here ...
except RPCError, e:
    print str(e)
```
